version: '3'
services:
  psql:
    image: postgres:15.3
    container_name: db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5438:5432'